export * from './icon_add'
export * from './icon_menu'
export * from './icon_coat'
export * from './icon_print'
export * from './icon_delete'
export * from './icon_edit_square'
export * from './icon_stick_note_2'
export * from './icon_account_circle'